"""
Model Configuration Summary
Provides an overview of current parameter settings and model structure
"""

print("=" * 80)
print("FINANCIAL MODEL CONFIGURATION SUMMARY")
print("=" * 80)

print("\n📋 MODEL SCOPE")
print("-" * 80)
print(f"Time Horizon: 60 months (5 years)")
print(f"Base Currency: GBP (£)")
print(f"Model Type: Bottom-up SaaS financial projection")
print(f"Revenue Streams: 5 (Subscription, Token Overage, Token PAYG, Invoice Finance, Enterprise)")

print("\n💰 CURRENT PRICING CONFIGURATION")
print("-" * 80)
print(f"Starter Tier:     £495/month,  300 tokens included")
print(f"Growth Tier:      £1,895/month, 1,250 tokens included")
print(f"Scale Tier:       £4,950/month, 5,000 tokens included")
print(f"Enterprise Tier:  £15,000/month, custom tokens")

print("\n📊 CHURN ASSUMPTIONS")
print("-" * 80)
print(f"Starter:     3.5%/month (35% annual churn)")
print(f"Growth:      2.2%/month (24% annual churn)")
print(f"Scale:       1.1%/month (12% annual churn)")
print(f"Enterprise:  0.6%/month (7% annual churn)")

print("\n💸 CUSTOMER ACQUISITION COST")
print("-" * 80)
print(f"Stealth/Partnerships:  £450")
print(f"Beta/Digital:          £1,200")
print(f"Launch/Mixed:          £3,500")
print(f"Enterprise/Outbound:   £8,500")

print("\n🪙 TOKEN ECONOMICS")
print("-" * 80)
print(f"PAYG Rate:        £2.00/token")
print(f"Overage Rate:     £1.50/token")
print(f"Rollover Period:  90 days")

print("\n🧾 INVOICE FINANCE RATES")
print("-" * 80)
print(f"Institutional:    1.5%-3.0% take rate")
print(f"P2P Platform:     2.0%-4.0% platform fee")
print(f"Expected Loss:    2.5%")
print(f"Launch Timeline:  Institutional Y2 Q3, P2P Y3 Q4")

print("\n🌍 GEOGRAPHIC EXPANSION")
print("-" * 80)
print(f"UK:   1.0x baseline (Year 1)")
print(f"EU:   2.3x baseline (Year 2)")
print(f"US:   4.1x baseline (Year 3)")
print(f"APAC: 1.8x baseline (Year 4+)")

print("\n🎯 KEY MODEL DRIVERS")
print("-" * 80)
print(f"✓ Customer Acquisition:   By GTM phase (Stealth → Beta → Launch)")
print(f"✓ Cohort Tracking:        Survival analysis with monthly churn")
print(f"✓ Tier Upgrades:          Conversion rates: Starter→Growth (18%), Growth→Scale (9%)")
print(f"✓ Seat Expansion:         Within-tier growth (3-4.5% monthly rate)")
print(f"✓ Token Consumption:      By company size and use case")
print(f"✓ Invoice Pool Growth:    S-curve to critical mass by Y2 end")

print("\n📈 TARGET METRICS")
print("-" * 80)
print(f"ARR Milestone:    £10M by Y3, £100M by Y5")
print(f"GRR Target:       92-95%")
print(f"NRR Target:       110-120%")
print(f"LTV:CAC Target:   3-5x")
print(f"CAC Payback:      <12 months")
print(f"Rule of 40:       ≥40 by Y3")

print("\n🔧 EDITABLE INPUT BLOCKS")
print("-" * 80)
print(f"1. inputs.pricing_tiers       - Subscription prices & token allocations")
print(f"2. inputs.churn_rates          - Monthly churn by tier")
print(f"3. inputs.cac_by_segment       - Customer acquisition cost by channel")
print(f"4. inputs.volume_assumptions   - Customer density & conversion rates")
print(f"5. inputs.token_economics      - Token pricing & consumption")
print(f"6. inputs.invoice_finance      - Discount rates & loss provisions")
print(f"7. inputs.regional_expansion   - Geographic market multipliers")

print("\n📤 OUTPUT BLOCKS")
print("-" * 80)
print(f"• dashboard.executive_summary    - Key investor metrics")
print(f"• dashboard.arr_mrr_overview     - ARR/MRR trends & growth")
print(f"• export.monthly_revenue_by_stream    - 60-month revenue detail")
print(f"• export.customer_counts         - Customer counts by tier")
print(f"• export.executive_metrics       - GRR, NRR, LTV:CAC")
print(f"• export.geographic_breakdown    - Regional revenue split")
print(f"• scenarios.comparison_view      - Scenario side-by-side")

print("\n📚 DOCUMENTATION BLOCKS")
print("-" * 80)
print(f"• documentation.user_guide        - Full parameter guide & workflows")
print(f"• documentation.quick_reference   - Cheat sheet for common tasks")
print(f"• documentation.model_summary     - This block (configuration overview)")

print("\n✅ MODEL STATUS")
print("-" * 80)
print(f"Configuration:    ✓ Complete")
print(f"Baseline Run:     ✓ Executed")
print(f"Validation:       ✓ Passed")
print(f"Exports:          ✓ Generated")
print(f"Documentation:    ✓ Available")

print("\n" + "=" * 80)
print("🚀 Ready for scenario testing and parameter adjustment")
print("📖 See documentation.user_guide for detailed instructions")
print("=" * 80)
